src/BlogBundle/Entity/Category.php
<?php

namespace BlogBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Category
 */
class Category
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $description;


    protected $entry;
    
    public function __construct() {
        $this->entry = new ArrayCollection();
                
    }

    public function __toString(){
        return $this->name;
    }

    public function getEntries() {
        return $this->entry;
    }
    
    
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Category
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
}

src/BlogBundle/Form/CategoryType.php
<?php

namespace BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class CategoryType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class, array("label"=>"Nombre:","required"=>"false", "attr" =>array(
				"class" => "form-name form-control",
			)))
            ->add('description',TextareaType::class, array("label"=>"Descripción:","required"=>"false", "attr" =>array(
				"class" => "form-name form-control",
			)))
            ->add('Guardar', SubmitType::class, array("attr" =>array(
				"class" => "form-submit btn btn-success",
			)))
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'BlogBundle\Entity\Category'
        ));
    }
}

src/BlogBundle/Controller/CategoryController.php
<?php

namespace BlogBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use BlogBundle\Entity\Category;
use BlogBundle\Form\CategoryType;


class CategoryController extends Controller
{
	private $session;
	
	public function __construct() {
		$this->session=new Session();
	}

	public function indexAction(){
		$em = $this->getDoctrine()->getEntityManager();
		$category_repo=$em->getRepository("BlogBundle:Category");
		$categories=$category_repo->findAll();
		
		return $this->render("BlogBundle:Category:index.html.twig",array(
			"categories" => $categories
		));
	}
	
	public function addAction(Request $request){
		$category = new Category();
		$form = $this->createForm(CategoryType::class,$category);
		
		$form->handleRequest($request);
		
		if($form->isSubmitted()){
			if($form->isValid()){
				
				$em = $this->getDoctrine()->getEntityManager();
				
				$category = new Category();
				$category->setName($form->get("name")->getData());
				$category->setDescription($form->get("description")->getData());
				
				$em->persist($category);
				$flush = $em->flush();
				
				if($flush==null){
					$status = "Categoria creada correctament";
				}else{
					$status ="Categoria no afegida";
				}
				
			}else{
				$status = "Categoria no afegida perquè el formulari no és vàlid";
			}
			
			$this->session->getFlashBag()->add("status", $status);
			return $this->redirectToRoute("blog_index_category");
		}
		
		
		return $this->render("BlogBundle:Category:add.html.twig",array(
			"form" => $form->createView()
		));
	}
	
	public function deleteAction($id){
		$em = $this->getDoctrine()->getEntityManager();
		$category_repo=$em->getRepository("BlogBundle:Category");
		$category=$category_repo->find($id);
		
		if(count($category->getEntries())==0){
			$em->remove($category);
			$em->flush();
		}
		
		return $this->redirectToRoute("blog_index_category");
	}
        public function editAction(Request $request, $id){
		$em = $this->getDoctrine()->getEntityManager();
		$category_repo=$em->getRepository("BlogBundle:Category");
		$category=$category_repo->find($id);
		
		$form = $this->createForm(CategoryType::class,$category);
		
		$form->handleRequest($request);
		
		if($form->isSubmitted()){
			if($form->isValid()){
				
				$category->setName($form->get("name")->getData());
				$category->setDescription($form->get("description")->getData());
				
				$em->persist($category);
				$flush = $em->flush();
				
				if($flush==null){
					$status = "La categoria se ha editado correctamente !!";
				}else{
					$status ="Error al editar la categoria!!";
				}
				
			}else{
				$status = "La categoria no s'ha editat, porque el formulario no és vàlido !!";
			}
			
			$this->session->getFlashBag()->add("status", $status);
			return $this->redirectToRoute("blog_index_category");
		}
		
		return $this->render("BlogBundle:Category:edit.html.twig",array(
			"form" => $form->createView()
		));
	}	
}

src/BlogBundle/Resources/views/Category/add.html.twig
{% extends "BlogBundle::layout.html.twig"%}
{% block content %}
            
    <div class="col-lg-6">
        <h2>Afegir Categories</h2> 
        <hr/>
        {{form_start(form, {'action':'', 'method':'POST'})}}
        {{form_end(form)}}
    </div>
            
    <div class="clearfix"></div>
{% endblock %}

src/BlogBundle/Resources/views/Category/edit.html.twig
{% extends "BlogBundle::layout.html.twig"%}
{% block content %}
            
    <div class="col-lg-6">
        <h2>Ediar Categoria</h2> 
        <hr/>
        {{form_start(form)}}
        {{form_end(form)}}
    </div>
            
    <div class="clearfix"></div>
{% endblock %}

src/BlogBundle/Resources/views/Category/index.html.twig
{% extends "BlogBundle::layout.html.twig" %}

{% block content %}
    <div class="col-lg-6">
        <h2>Llistat Categories</h2>
        <hr/>
        <a href="{{path("blog_add_category")}}" class="btn btn-success">Afegir categoria</a>
        <hr/>
        {% for message in app.session.flashbag().get('status') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
        <table class="table table-bordered">
            <tr>
                <th>Nom</th>
                <th>Descripció</th>
                <th>Editar</th>
                 <th>Esborrar</th>
            </tr>
            {% for category in categories %}
                <tr>
                    <td>{{ category.name }}</td>
                    <td>{{ category.description }}</td>
                    <td><a href="{{path("blog_edit_category", {"id":category.id})}}" class="btn btn-warning">Editar</a></td>
                    <td>
                        {% if category.entries|length == 0 %}
                            <a href="{{path("blog_delete_category", {"id":category.id})}}" class="btn btn-danger">Eliminar</a>
                        {% else %} 
                           Categoria en uso
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="clearfix"></div>
{% endblock %}